datana:
  producer:
    topic: KafkaDatanaDemoTopic
  consumer:
    topic: KafkaDatanaDemoTopic
    group: KafkaDatanaGroup
    maxPollRecords: 5000
    partitionValue: 0
  period: 1000

camel:
  component:
    activemq:
      broker-url: tcp://localhost:61616
  springboot:
    main-run-controller: true
spring:
  kafka:
    bootstrap-servers: localhost:9092

