datana:
  producer:
    topic: KafkaDatanaDemoTopic
  consumer:
    topic: KafkaDatanaDemoTopic
    group: KafkaDatanaGroup
    maxPollRecords: 5000
    partitionValue: 0
  period: 1000
  global:
    beauty-json: true
    experimental-s7-algorithm: false
    log:
      level: INFO

camel:
  springboot:
    main-run-controller: true
spring:
  kafka:
    bootstrap-servers: 172.29.40.42:9092

logging:
  level:
    root: ${datana.global.log.level}
    org:
      apache:
        tomcat:
          util: INFO
      springframework: ${datana.global.log.level}
    ru:
      datana: ${datana.global.log.level}
    sun: INFO
    javax: INFO
  file:
    ###name: ${app.dir}/server-logs/plc-server.log
    name: ~/apps/server-logs/camel-server.log
    max-size: 64 MB
    total-size-cap: 512 MB
  pattern:
    rolling-file-name:  ~/apps/archive-server-logs/camel-server-archive.%d{yyyy-MM-dd}.%i.gz



