datana:
  producer:
    topic: KafkaDatanaDemoTopic
  consumer:
    topic: KafkaDatanaDemoTopic
    group: KafkaDatanaGroup
    maxPollRecords: 5000
    partitionValue: 0
  period: 1000
  global:
    beauty-json: true
    experimental-s7-algorithm: false

camel:
  springboot:
    main-run-controller: true
spring:
  kafka:
    bootstrap-servers: 172.29.40.42:9092

