##### Configuration for PLC SERVER #####
datana:
  activemq:
    # url jms брокера
    brokerUrl: tcp://localhost:61616
    # очередь запросов
    requestQueue: jmsFromPLC

    # очередь ответов
    responseQueue: jmsResponseFromDatanaToPLC

    # очередь ошибок
    responseQueueOnError: jmsFromPLCToError

    # количество обработчиков JMS в отдельных потоках
    listener-count: 15
  global:
    log:
      # уровень вывода логов
      level: INFO
    beauty-json: true

### НИЖЕ НЕ РЕДАКТИРОВАТЬ ПОЛЬЗОВАТЕЛЯМ !!!! ####
spring:
  main:
    web-application-type: none
    banner-mode: off
    testWhileIdle: true
### logging ###
logging:
  level:
    root: ${datana.global.log.level}
    executableSql: ${datana.global.log.level}
    org:
      apache:
        tomcat:
          util: INFO
      hibernate:
        engine:
          transaction: ${datana.global.log.level}
        SQL: ${datana.global.log.level}
      springframework:
        web: ${datana.global.log.level}
    ru:
      datana: DEBUG
    sun: INFO
    javax: INFO
  file:
    name: ${app.dir}/datana-server-logs/plc-gatemway.log
    max-size: 16 MB
    total-size-cap: 128 MB
  pattern:
    rolling-file-name:  ${app.dir}/datana-archive-plc-logs/mes-gateway-archive.%d{yyyy-MM-dd}.%i.log



