##### Configuration for PLC SERVER #####
datana:
  global:
    debug: false
    log:
      level: WARN
    beauty-json: false
    experimental-s7-algorithm: false

### НИЖЕ НЕ РЕДАКТИРОВАТЬ ПОЛЬЗОВАТЕЛЯМ !!!! ####
spring:
  main:
    banner-mode: off
#### logging ###
logging:
  level:
    root: ${datana.global.log.level}
    executableSql: ${datana.global.log.level}
    org:
      apache:
        tomcat:
          util: WARN
      hibernate:
        engine:
          transaction: ${datana.global.log.level}
        SQL: ${datana.global.log.level}
      springframework:
        web: ${datana.global.log.level}
    ru:
      datana: WARN
    sun: WARN
    javax: WARN
  file:
    ###name: ${app.dir}/server-logs/plc-server.log
    name: ~/apps/server-logs/plc-server.log
    max-size: 64 MB
    total-size-cap: 512 MB
  pattern:
    rolling-file-name:  ~/apps/archive-server-logs/plc-server-archive.%d{yyyy-MM-dd}.%i.log



