##### Configuration for PLC SERVER #####
datana:
  activemq:
    brokerUrl: tcp://localhost:61616
    requestQueue: jmsFromPLC
    responseQueue: jmsResponseFromDatanaToPLC
    responseQueueOnError: jmsFromPLCToError
  global:
    debug: true
    log:
      # уровень вывода логов
      level: DEBUG
    beauty-json: true
    experimental-s7-algorithm: false

### НИЖЕ НЕ РЕДАКТИРОВАТЬ ПОЛЬЗОВАТЕЛЯМ !!!! ####
spring:
  main:
    web-application-type: none
    banner-mode: off
    testWhileIdle: true
### logging ###
logging:
  level:
    root: ${datana.global.log.level}
    executableSql: ${datana.global.log.level}
    org:
      apache:
        tomcat:
          util: INFO
      hibernate:
        engine:
          transaction: ${datana.global.log.level}
        SQL: ${datana.global.log.level}
      springframework:
        web: ${datana.global.log.level}
    ru:
      datana: DEBUG
    sun: INFO
    javax: INFO
  file:
    name: ${app.dir}/client-logs/mes-gatemway.log
    max-size: 16 MB
    total-size-cap: 128 MB
  pattern:
    rolling-file-name:  ${app.dir}/archive-mes-logs/mes-gateway-archive.%d{yyyy-MM-dd}.%i.log



