security:
    protocol: SSL
ssl:
    endpoint:
        identification:
            algorithm: ''
    key:
        password: 12345678
    keystore:
        location: /home/lin/apps/bin-gen-ssl-keys/keystore-client.jks
        password: 12345678
        type: JKS
    protocol: TLS
    secure:
        random:
            implementation: SHA1PRNG
    trustmanager:
        algorithm: PKIX
    truststore:
        location: /home/lin/apps/jdk13/lib/security/cacerts
        password: changeit
        type: JKS
